### ISSUE TITLE
How to define multiple assignements

### ISSUE THREAD

**Issue by poitch** [ryantate/rturk#21]
Looking at the README I see that you define 2 assignments for the tagging hit and later on the URL contains an item_id, I was wondering how one defines multiple assignments and the corresponding ids.

The examples has only one assignment and well the rdoc is pretty light.

**Comment by mdp** [comment]
Assignments just mean you'll have two workers 'tagging' the same item_id. This is good if you want to get more than one answer for a particular item.

"A HIT can have multiple assignments. This is useful for gathering multiple answers to a single question for comparison, or for collecting multiple opinions. A Worker can only accept a HIT once, so a HIT with multiple assignments is guaranteed to be performed by multiple Workers."

There's no rdoc because it's just a wrapper for the MTurk API. The better docs are the ones provided by amazon here: http://docs.amazonwebservices.com/AWSMechTurk/latest/AWSMechanicalTurkRequester/
